# docker-compose.yml
version: '3'
services:
  web3-wallet:
    container_name: web3-wallet
    image: nginx
    ports:
      - 8090:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf